### ISSUE TITLE
SWC compilation creates regression on 4.4.0

### ISSUE THREAD

**Issue by RealityAnomaly** [tommy351/kubernetes-models-ts#214]
**Describe the bug**
After upgrading from 4.3.2 to 4.4.0, I can no longer import any API models. It appears that the generated `index.js` files are attempting to import `.js` files (i.e. `v1beta1.js`) which do not exist. I'm not exactly sure why this is the case, but it seems to have something to do with the fact that the models are now compiled using swc.

```
Error: Cannot find module './v1beta1.js'
Require stack:
- node_modules/kubernetes-models/admissionregistration.k8s.io/index.js
- node_modules/kubernetes-models/index.js
```

Could it be possible that in some implementations of import systems this bug can be handled and thus it slipped through?

**To Reproduce**
Attempt to import any model from `kubernetes-models` with an import statement.

**Expected behavior**
The module should have been imported.

**Additional context**
I am running my program with ts-node and swc with direct transpilation. I haven't tested any other methods.

**Comment by RealityAnomaly** [comment]
I opened https://github.com/tommy351/kubernetes-models-ts/pull/216, which should close this issue.
